# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

kernel:
    resource: ../src/Kernel.php
    type: attribute

home_page:
    path: /
    controller: 'App\Controller\HomePageController::homeNoLocale'

registeration_page:
    path: /register
    controller: 'App\Controller\RegisterController::registerNoLocal'

user_registeration_page:
    path: /user/register
    controller: 'App\Controller\RegisterController::users_register'
    methods: [ 'GET', 'POST' ]

devices_page:
    path: /devices
    controller: 'App\Controller\DevicesController::devicesNoLocal'

user_devices_page:
    path: /user/devices
    controller: 'App\Controller\DevicesController::index'
    methods: [ 'GET', 'POST' ]

profile_page:
    path: /profile
    controller: 'App\Controller\UserProfileController::profileNoLocal'

user_profile_page:
    path: /user/profile
    controller: 'App\Controller\UserProfileController::index'
    methods: [ 'GET', 'POST' ]

settings_page:
    path: /settings
    controller: 'App\Controller\UserSettingsController::userSettingsNoLocal'

user_settings_page:
    path: /user/settings
    controller: 'App\Controller\UserSettingsController::index'
    methods: [ 'GET', 'POST' ]
